name: Go

on:
  push:
  pull_request:

jobs:

  runner-job:
  
    runs-on: ubuntu-latest
    
    services:
      godb:
        image: laidlawm/godb
        ports:
        - 6342:6342
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
